# PROBLEM 045


"""Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal."""

# initilize the counters and the lists
t, n, h = 286, 166, 144
T, P, H = [], [], []


while t < (100000):
    T.append(int(t*(t+1)/2))
    t +=1
while n < (100000):
	P.append(int(n*(3*n-1)/2))
	n +=1
while h < (100000):
	H.append(int(h*(2*h-1)))
	h +=1

for k in T:
	if k in P and k in H:
		print (k)
		break